# Generated by Django 4.0.3 on 2022-03-24 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=225)),
                ('typedescription', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'musictype',
            },
        ),
        migrations.CreateModel(
            name='MusicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=225)),
                ('releaseDate', models.DateField()),
                ('YoutubeURL', models.URLField()),
                ('musicdescription', models.TextField()),
                ('musictype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.musictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'musicname',
            },
        ),
    ]
