# Generated by Django 4.0.3 on 2022-03-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
